import type { CapProfileName, CapSpec, SectionKind } from "./types.ts";

function cap(
  id: string,
  he: string,
  en: string,
  profile: CapProfileName,
  section: SectionKind,
  h: number,
  w: number,
  overhang: number,
  softness: number,
  faceted: boolean,
  tags: string[],
  depth = w,
): CapSpec {
  return {
    id,
    name: { he, en },
    section,
    profile,
    heightMm: h,
    widthMm: w,
    depthMm: depth,
    overhangMm: overhang,
    softness,
    faceted,
    tags,
    model: { type: "procedural" },
  };
}

/** Overcaps. Width is the design diameter; the fitter widens anything that would miss the collar. */
export const CAPS: CapSpec[] = [
  cap("cap-cyl-22", "גליל נמוך", "Low cylinder", "cylinder", "circle", 22, 20, 1.4, 1, false, ["cylinder", "גליל", "classic", "קלאסי", "short"]),
  cap("cap-cyl-32", "גליל", "Cylinder", "cylinder", "circle", 32, 22, 1.6, 1, false, ["cylinder", "גליל", "classic", "קלאסי"]),
  cap("cap-cyl-42", "גליל גבוה", "Tall cylinder", "cylinder", "circle", 44, 22, 1.5, 1, false, ["cylinder", "גליל", "tall", "גבוה", "classic"]),
  cap("cap-cyl-56", "גליל ארוך", "Long cylinder", "cylinder", "circle", 58, 24, 1.8, 1, false, ["cylinder", "גליל", "tall", "גבוה"]),
  cap("cap-cyl-wide", "גליל רחב", "Wide cylinder", "cylinder", "circle", 30, 32, 3, 1, false, ["cylinder", "גליל", "wide", "רחב"]),
  cap("cap-dome-28", "כיפה", "Dome", "dome", "circle", 28, 24, 2, 1, false, ["dome", "כיפה"]),
  cap("cap-dome-40", "כיפה גבוהה", "Tall dome", "dome", "circle", 42, 26, 2.2, 1, false, ["dome", "כיפה", "tall"]),
  cap("cap-dome-slim", "כיפה צרה", "Slim dome", "dome", "circle", 48, 20, 1.2, 1, false, ["dome", "כיפה", "slim"]),
  cap("cap-sphere", "כדור", "Sphere", "sphere", "circle", 26, 26, 2, 1, false, ["sphere", "כדור", "ball"]),
  cap("cap-sphere-lg", "כדור גדול", "Large sphere", "sphere", "circle", 34, 34, 3, 1, false, ["sphere", "כדור", "ball", "large"]),
  cap("cap-sphere-flat", "כדור פחוס", "Flattened sphere", "sphere", "circle", 20, 30, 2.4, 1, false, ["sphere", "כדור", "flat"]),
  cap("cap-puck", "דיסקית", "Puck", "puck", "circle", 14, 28, 2.5, 1, false, ["puck", "דיסק", "short", "נמוך"]),
  cap("cap-puck-wide", "דיסקית רחבה", "Wide puck", "puck", "circle", 12, 36, 4, 1, false, ["puck", "דיסק", "wide"]),
  cap("cap-cone", "חרוט", "Cone", "cone", "circle", 36, 24, 1.6, 1, false, ["cone", "חרוט"]),
  cap("cap-cone-tall", "חרוט גבוה", "Tall cone", "cone", "circle", 52, 26, 1.8, 1, false, ["cone", "חרוט", "tall"]),
  cap("cap-cone-low", "חרוט נמוך", "Low cone", "cone", "circle", 24, 28, 2, 1, false, ["cone", "חרוט", "short"]),
  cap("cap-bell", "פעמון", "Bell cap", "bell", "circle", 32, 28, 2.4, 1, false, ["bell", "פעמון"]),
  cap("cap-bell-tall", "פעמון גבוה", "Tall bell", "bell", "circle", 46, 30, 2.6, 1, false, ["bell", "פעמון", "tall"]),
  cap("cap-obelisk", "אובליסק", "Obelisk", "obelisk", "circle", 48, 22, 1.4, 1, false, ["obelisk", "אובליסק", "tall"]),
  cap("cap-obelisk-sq", "אובליסק מרובע", "Square obelisk", "obelisk", "rect", 50, 22, 1.4, 0.35, false, ["obelisk", "אובליסק", "square", "מרובע"]),
  cap("cap-taper", "מחודד", "Taper", "taper", "circle", 40, 24, 1.6, 1, false, ["taper", "מחודד"]),
  cap("cap-taper-wide", "מחודד רחב", "Wide taper", "taper", "circle", 34, 32, 2.8, 1, false, ["taper", "מחודד", "wide"]),
  cap("cap-mag-36", "מגנטי", "Magnetic", "magnetic", "circle", 38, 22, 1.5, 1, false, ["magnetic", "מגנטי", "seam"]),
  cap("cap-mag-50", "מגנטי גבוה", "Tall magnetic", "magnetic", "circle", 52, 24, 1.7, 1, false, ["magnetic", "מגנטי", "tall", "גבוה"]),
  cap("cap-mag-sq", "מגנטי מרובע", "Square magnetic", "magnetic", "rect", 42, 24, 1.6, 0.4, false, ["magnetic", "מגנטי", "square", "מרובע"]),
  cap("cap-mushroom", "פטרייה", "Mushroom", "mushroom", "circle", 30, 28, 2.2, 1, false, ["mushroom", "פטרייה"]),
  cap("cap-mushroom-lg", "פטרייה רחבה", "Wide mushroom", "mushroom", "circle", 28, 36, 3.5, 1, false, ["mushroom", "פטרייה", "wide"]),
  cap("cap-facet-6", "פאות", "Faceted", "facet", "hex", 36, 24, 1.6, 0.2, true, ["facet", "פאות", "crystal", "קריסטל", "hex"]),
  cap("cap-facet-8", "פאות מתומן", "Octa facet", "facet", "oct", 40, 26, 1.8, 0.2, true, ["facet", "פאות", "oct", "crystal"]),
  cap("cap-facet-tall", "פאות גבוה", "Tall facet", "facet", "hex", 56, 22, 1.4, 0.15, true, ["facet", "פאות", "tall", "crystal"]),
  cap("cap-crystal", "קריסטל", "Crystal", "crystal", "oct", 34, 26, 2, 0.15, true, ["crystal", "קריסטל", "facet", "פאות"]),
  cap("cap-crystal-gem", "אבן חן", "Gem cap", "crystal", "diamond", 38, 28, 2.2, 0.12, true, ["crystal", "קריסטל", "gem", "יהלום", "diamond"]),
  cap("cap-crystal-sm", "קריסטל קטן", "Small crystal", "crystal", "hex", 24, 22, 1.3, 0.2, true, ["crystal", "קריסטל", "small"]),
  cap("cap-wood", "פקק עץ", "Wood stopper", "woodstop", "circle", 28, 22, 1.2, 1, false, ["wood", "עץ", "wooden", "stopper"]),
  cap("cap-wood-tall", "עץ גבוה", "Tall wood", "woodstop", "circle", 42, 24, 1.4, 1, false, ["wood", "עץ", "tall"]),
  cap("cap-wood-wide", "עץ רחב", "Wide wood", "woodstop", "circle", 24, 32, 2.6, 1, false, ["wood", "עץ", "wide"]),
  cap("cap-cube", "קובייה", "Cube", "cube", "rect", 24, 24, 1.8, 0.28, false, ["cube", "קובייה", "קוביה", "square"]),
  cap("cap-cube-tall", "קובייה גבוהה", "Tall cube", "cube", "rect", 40, 26, 2, 0.25, false, ["cube", "קובייה", "tall", "square"]),
  cap("cap-cube-soft", "קובייה רכה", "Soft cube", "cube", "squircle", 28, 28, 2.2, 0.7, false, ["cube", "קובייה", "soft", "רך"]),
  cap("cap-cube-flat", "לוח", "Slab", "cube", "rect", 16, 34, 3, 0.3, false, ["cube", "slab", "לוח", "flat"]),
  cap("cap-arch", "קשת", "Arch cap", "arch", "squircle", 36, 26, 2, 0.65, false, ["arch", "קשת"]),
  cap("cap-arch-wide", "קשת רחבה", "Wide arch", "arch", "oval", 30, 36, 3, 0.7, false, ["arch", "קשת", "wide"], 28),
  cap("cap-bullet", "קליע", "Bullet", "bullet", "circle", 40, 22, 1.4, 1, false, ["bullet", "קליע"]),
  cap("cap-bullet-lg", "קליע גדול", "Large bullet", "bullet", "circle", 48, 28, 2.2, 1, false, ["bullet", "קליע", "large"]),
  cap("cap-oval-cyl", "גליל אובלי", "Oval cylinder", "cylinder", "oval", 36, 30, 2, 0.8, false, ["oval", "אובל", "cylinder"], 22),
  cap("cap-oval-dome", "כיפה אובלית", "Oval dome", "dome", "oval", 32, 34, 2.4, 0.85, false, ["oval", "אובל", "dome"], 24),
  cap("cap-diamond", "יהלום", "Diamond cap", "facet", "diamond", 36, 26, 1.8, 0.15, true, ["diamond", "יהלום", "facet"]),
  cap("cap-hex-puck", "משושה נמוך", "Hex puck", "puck", "hex", 16, 30, 2.4, 0.2, true, ["hex", "משושה", "puck"]),
  cap("cap-oct-cyl", "מתומן", "Octagon cap", "cylinder", "oct", 34, 24, 1.6, 0.2, true, ["oct", "מתומן", "facet"]),
  cap("cap-crown", "כתר", "Crown taper", "taper", "oct", 30, 30, 2.6, 0.25, true, ["crown", "כתר", "facet", "oct"]),
  // FEA 15 overcaps. Diameters sit just over a 16.3 mm ferrule; the fitter widens anything that would miss the collar.
  cap("zamac-disc", "זמק דיסק", "Zamac disc", "puck", "circle", 14, 24, 1.6, 0.35, false, ["zamac", "זמק", "zinc", "metal", "puck"]),
  cap("zamac-low", "זמק נמוך", "Low zamac", "cylinder", "circle", 20, 22, 1.5, 0.4, false, ["zamac", "זמק", "zinc", "cylinder"]),
  cap("zamac-cyl", "זמק גליל", "Zamac cylinder", "cylinder", "circle", 32, 22, 1.6, 0.25, false, ["zamac", "זמק", "zinc", "cylinder"]),
  cap("zamac-tall", "זמק גבוה", "Tall zamac", "cylinder", "circle", 46, 23, 1.7, 0.2, false, ["zamac", "זמק", "zinc", "tall"]),
  cap("zamac-cube", "זמק קובייה", "Zamac cube", "cube", "rect", 26, 24, 1.8, 0.22, false, ["zamac", "זמק", "zinc", "cube"]),
  cap("zamac-sq", "זמק מרובע", "Square zamac", "cube", "rect", 38, 24, 1.8, 0.18, false, ["zamac", "זמק", "zinc", "square", "tall"]),
  cap("zamac-dome", "זמק כיפה", "Zamac dome", "dome", "circle", 30, 26, 2, 0.45, false, ["zamac", "זמק", "zinc", "dome"]),
  cap("zamac-facet", "זמק פאות", "Faceted zamac", "facet", "hex", 36, 24, 1.7, 0.12, true, ["zamac", "זמק", "zinc", "facet"]),
  cap("surlyn-puck", "סורלין דיסק", "Surlyn puck", "puck", "circle", 13, 30, 2.4, 0.85, false, ["surlyn", "סורלין", "puck", "light"]),
  cap("surlyn-dome", "סורלין כיפה", "Surlyn dome", "dome", "circle", 26, 28, 2.2, 0.9, false, ["surlyn", "סורלין", "dome"]),
  cap("surlyn-cyl", "סורלין גליל", "Surlyn cylinder", "cylinder", "circle", 24, 26, 2, 0.8, false, ["surlyn", "סורלין", "cylinder"]),
  cap("surlyn-wide", "סורלין רחב", "Wide surlyn", "cylinder", "circle", 22, 34, 3.2, 0.75, false, ["surlyn", "סורלין", "wide"]),
  cap("surlyn-soft", "סורלין רך", "Soft surlyn", "cube", "squircle", 22, 30, 2.4, 0.8, false, ["surlyn", "סורלין", "soft"]),
  cap("surlyn-oval", "סורלין אובל", "Oval surlyn", "cylinder", "oval", 24, 32, 2.2, 0.85, false, ["surlyn", "סורלין", "oval"], 24),
  cap("wood-short", "עץ קצר", "Short wood", "woodstop", "circle", 18, 22, 1.3, 0.7, false, ["wood", "עץ", "short", "stopper"]),
  cap("wood-column", "עץ עמוד", "Wood column", "woodstop", "circle", 40, 22, 1.4, 0.55, false, ["wood", "עץ", "tall", "column"]),
  cap("wood-barrel", "עץ חבית", "Wood barrel", "woodstop", "circle", 28, 28, 2.2, 0.8, false, ["wood", "עץ", "barrel"]),
  cap("wood-cube", "עץ קובייה", "Wood cube", "cube", "rect", 26, 24, 1.6, 0.35, false, ["wood", "עץ", "cube"]),
  cap("wood-dome", "עץ כיפה", "Wood dome", "dome", "circle", 30, 26, 1.8, 0.7, false, ["wood", "עץ", "dome"]),
  cap("wood-oval", "עץ אובלי", "Oval wood", "woodstop", "oval", 26, 32, 2.2, 0.75, false, ["wood", "עץ", "oval"], 24),
  cap("acry-gem", "אקריליק אבן", "Acrylic gem", "crystal", "diamond", 36, 26, 2, 0.12, true, ["acrylic", "אקריליק", "crystal", "gem"]),
  cap("acry-column", "אקריליק עמוד", "Acrylic column", "facet", "hex", 50, 22, 1.5, 0.15, true, ["acrylic", "אקריליק", "crystal", "tall"]),
  cap("acry-disc", "אקריליק דיסק", "Acrylic disc", "puck", "oct", 14, 32, 2.6, 0.2, true, ["acrylic", "אקריליק", "crystal", "puck"]),
  cap("acry-sphere", "אקריליק כדור", "Acrylic sphere", "sphere", "circle", 28, 28, 2.2, 0.3, true, ["acrylic", "אקריליק", "crystal", "sphere"]),
  cap("acry-obelisk", "אקריליק אובליסק", "Acrylic obelisk", "obelisk", "oct", 52, 22, 1.4, 0.15, true, ["acrylic", "אקריליק", "crystal", "tall"]),
  cap("acry-oct", "אקריליק מתומן", "Acrylic octagon", "cylinder", "oct", 32, 26, 1.8, 0.18, true, ["acrylic", "אקריליק", "crystal", "oct"]),
  cap("mag-flush", "מגנט שטוח", "Flush magnetic", "magnetic", "circle", 20, 22, 1.4, 0.4, false, ["magnetic", "מגנטי", "flush", "seam"]),
  cap("mag-column", "מגנט עמוד", "Magnetic column", "magnetic", "circle", 48, 23, 1.6, 0.3, false, ["magnetic", "מגנטי", "tall"]),
  cap("mag-square", "מגנט ריבוע", "Square magnet", "magnetic", "rect", 34, 26, 1.7, 0.28, false, ["magnetic", "מגנטי", "square"]),
  cap("mag-dome", "מגנט כיפה", "Magnetic dome", "magnetic", "circle", 30, 28, 2.1, 0.55, false, ["magnetic", "מגנטי", "dome"]),
  cap("mag-wide", "מגנט רחב", "Wide magnetic", "magnetic", "circle", 22, 34, 2.8, 0.4, false, ["magnetic", "מגנטי", "wide"]),
  cap("mag-slim", "מגנט צר", "Slim magnetic", "magnetic", "circle", 42, 20, 1.2, 0.35, false, ["magnetic", "מגנטי", "slim"]),
  cap("sculp-orb", "כדור פיסולי", "Sculptural orb", "sphere", "circle", 34, 34, 2.8, 0.6, false, ["sculptural", "פיסולי", "sphere"]),
  cap("sculp-mushroom", "פטרייה פיסולית", "Sculptural mushroom", "mushroom", "circle", 28, 36, 3.2, 0.7, false, ["sculptural", "פיסולי", "mushroom"]),
  cap("sculp-bell", "פעמון פיסולי", "Sculptural bell", "bell", "circle", 42, 30, 2.4, 0.65, false, ["sculptural", "פיסולי", "bell"]),
  cap("sculp-obelisk", "אובליסק פיסולי", "Sculptural obelisk", "obelisk", "rect", 56, 22, 1.4, 0.3, false, ["sculptural", "פיסולי", "obelisk", "tall"]),
  cap("sculp-arch", "קשת פיסולית", "Sculptural arch", "arch", "squircle", 38, 28, 2, 0.7, false, ["sculptural", "פיסולי", "arch"]),
  cap("sculp-bullet", "קליע פיסולי", "Sculptural bullet", "bullet", "circle", 48, 24, 1.6, 0.5, false, ["sculptural", "פיסולי", "bullet"]),
  cap("min-slab", "לוח מינימל", "Minimal slab", "cube", "rect", 12, 32, 2.6, 0.2, false, ["minimal", "מינימל", "slab", "flat"]),
  cap("min-puck", "דיסק מינימל", "Minimal puck", "puck", "circle", 11, 26, 1.8, 0.5, false, ["minimal", "מינימל", "puck"]),
  cap("min-band", "טבעת מינימל", "Minimal band", "cylinder", "circle", 16, 22, 1.3, 0.3, false, ["minimal", "מינימל", "band"]),
  cap("min-square", "ריבוע מינימל", "Minimal square", "cube", "rect", 16, 24, 1.5, 0.22, false, ["minimal", "מינימל", "square"]),
  cap("min-oval", "אובל מינימל", "Minimal oval", "puck", "oval", 12, 32, 2.2, 0.8, false, ["minimal", "מינימל", "oval"], 22),
  cap("min-flush", "פקק מינימל", "Flush minimal", "cylinder", "circle", 18, 20, 1.2, 0.4, false, ["minimal", "מינימל", "flush"]),
];
