import type { LogoApplication, LogoFont, LogoFrame, LogoMark, LogoPlate, LogoSpec } from "./types.ts";

function logo(
  id: string,
  he: string,
  en: string,
  plate: LogoPlate,
  mark: LogoMark,
  application: LogoApplication,
  font: LogoFont,
  frame: LogoFrame,
  tags: string[],
): LogoSpec {
  return {
    id,
    name: { he, en },
    plate,
    mark,
    application,
    font,
    frame,
    tags: [application, mark, plate, font, ...tags],
    model: { type: "procedural" },
  };
}

export const LOGOS: LogoSpec[] = [
  logo("lg-foil-diamond", "יהלום זהב", "Foil diamond", "plaque", "diamond", "plaque", "cinzel", "corners", ["plaque", "זהב", "יהלום"]),
  logo("lg-foil-seal", "חותם זהב", "Foil seal", "circle", "seal", "plaque", "cinzel", "circle", ["seal", "חותם", "plaque"]),
  logo("lg-engrave-word", "מילה חרוטה", "Engraved word", "tall", "word", "engrave", "cormorant", "none", ["word", "מילה", "engrave", "חרוט"]),
  logo("lg-emboss-mono", "מונוגרמה מובלטת", "Embossed monogram", "square", "monogram", "sticker", "cinzel", "hairline", ["monogram", "מונוגרמה", "sticker"]),
  logo("lg-decal-horizon", "קו אופק", "Horizon", "plaque", "horizon", "decal", "italiana", "hairline", ["horizon", "אופק", "decal"]),
  logo("lg-foil-crest", "שלט זהב", "Foil crest", "arch", "crest", "plaque", "cinzel", "laurel", ["crest", "שלט", "plaque"]),
  logo("lg-engrave-drop", "טיפה חרוטה", "Engraved drop", "circle", "droplet", "engrave", "cormorant", "none", ["droplet", "טיפה", "engrave"]),
  logo("lg-foil-star", "כוכב זהב", "Foil star", "diamond", "star", "plaque", "cinzel", "corners", ["star", "כוכב", "plaque"]),
  logo("lg-decal-wave", "גלים", "Wave band", "band", "wave", "decal", "heebo", "hairline", ["wave", "גל", "band", "פס"]),
  logo("lg-emboss-stack", "שם מובלט", "Embossed stack", "tall", "stacked", "sticker", "cormorant", "double", ["stacked", "שם", "sticker"]),
  logo("lg-foil-laurel", "זר זהב", "Foil laurel", "circle", "laurel", "plaque", "cinzel", "laurel", ["laurel", "זר", "plaque"]),
  logo("lg-engrave-vert", "אנכי חרוט", "Vertical engrave", "tall", "vertical", "engrave", "cinzel", "none", ["vertical", "אנכי", "engrave"]),
  logo("lg-decal-dots", "נקודות", "Dot constellation", "plaque", "dots", "decal", "heebo", "none", ["dots", "נקודות"]),
  logo("lg-foil-deco", "אר דקו", "Art deco fan", "arch", "deco", "plaque", "italiana", "hairline", ["deco", "דקו", "plaque"]),
  logo("lg-emboss-oval", "אובל מובלט", "Embossed oval", "plaque", "oval", "sticker", "cormorant", "circle", ["oval", "אובל", "sticker"]),
  logo("lg-engrave-chevron", "שברון", "Chevron", "slim", "chevron", "engrave", "cinzel", "none", ["chevron", "שברון"]),
  logo("lg-foil-numeral", "מספר זהב", "Foil numeral", "square", "numeral", "plaque", "cinzel", "double", ["numeral", "מספר", "plaque"]),
  logo("lg-decal-bars", "פסים", "Fine bars", "slim", "bars", "decal", "heebo", "hairline", ["bars", "פסים"]),
  logo("lg-emboss-crest", "שלט מובלט", "Embossed crest", "arch", "crest", "sticker", "cinzel", "corners", ["crest", "sticker"]),
  logo("lg-engrave-mono", "מונוגרמה חרוטה", "Engraved monogram", "circle", "monogram", "engrave", "cinzel", "circle", ["monogram", "מונוגרמה", "engrave"]),
  logo("lg-foil-word", "מילה בזהב", "Foil word", "plaque", "word", "plaque", "italiana", "hairline", ["word", "plaque", "מילה"]),
  logo("lg-decal-diamond", "יהלום קווי", "Line diamond", "diamond", "diamond", "decal", "cinzel", "none", ["diamond", "יהלום"]),
  logo("lg-emboss-sun", "שמש מובלטת", "Embossed sun", "circle", "sun", "sticker", "italiana", "circle", ["sun", "שמש", "sticker"]),
  logo("lg-engrave-seal", "חותם חרוט", "Engraved seal", "circle", "seal", "engrave", "cinzel", "double", ["seal", "חותם", "engrave"]),
  logo("lg-foil-horizon", "אופק זהב", "Foil horizon", "slim", "horizon", "plaque", "cormorant", "none", ["horizon", "plaque"]),
  logo("lg-script-plaque", "כתב יד", "Script plaque", "plaque", "word", "decal", "vibes", "hairline", ["script", "כתב", "vibes"]),
  logo("lg-script-circle", "חותם כתב", "Script seal", "circle", "seal", "plaque", "vibes", "circle", ["script", "seal", "vibes"]),
  logo("lg-heebo-word", "מילה נקייה", "Clean word", "plaque", "word", "decal", "heebo", "none", ["word", "clean", "heebo"]),
  logo("lg-heebo-stack", "ערימה נקייה", "Clean stack", "tall", "stacked", "sticker", "heebo", "hairline", ["stacked", "heebo"]),
  logo("lg-double-foil", "שתי אותיות", "Two-letter foil", "square", "double", "plaque", "cinzel", "corners", ["double", "אותיות", "monogram"]),
  logo("lg-double-engrave", "אותיות חרוטות", "Two-letter engrave", "circle", "double", "engrave", "cormorant", "circle", ["double", "engrave"]),
  logo("lg-band-word", "פס מילה", "Word band", "band", "word", "decal", "cinzel", "none", ["band", "פס", "word"]),
  logo("lg-band-foil", "פס זהב", "Foil band", "band", "horizon", "plaque", "italiana", "hairline", ["band", "plaque"]),
  logo("lg-band-engrave", "פס חרוט", "Engraved band", "band", "bars", "engrave", "heebo", "none", ["band", "engrave"]),
  logo("lg-arch-laurel", "קשת וזר", "Arch laurel", "arch", "laurel", "sticker", "cormorant", "laurel", ["laurel", "arch"]),
  logo("lg-slim-numeral", "מספר דק", "Slim numeral", "slim", "numeral", "engrave", "cinzel", "hairline", ["numeral", "slim"]),
  logo("lg-tall-deco", "דקו אנכי", "Tall deco", "tall", "deco", "plaque", "italiana", "corners", ["deco", "tall"]),
  logo("lg-tall-drop", "טיפה אנכית", "Tall droplet", "tall", "droplet", "sticker", "cormorant", "none", ["droplet", "tall"]),
  logo("lg-square-star", "כוכב בריבוע", "Square star", "square", "star", "engrave", "cinzel", "double", ["star", "square"]),
  logo("lg-square-dots", "ריבוע נקודות", "Square dots", "square", "dots", "decal", "heebo", "corners", ["dots", "square"]),
  logo("lg-diamond-crest", "יהלום שלט", "Diamond crest", "diamond", "crest", "plaque", "cinzel", "laurel", ["crest", "diamond"]),
  logo("lg-diamond-mono", "יהלום אות", "Diamond monogram", "diamond", "monogram", "sticker", "cinzel", "corners", ["monogram", "diamond"]),
  logo("lg-circle-wave", "עיגול גלים", "Circle wave", "circle", "wave", "decal", "italiana", "circle", ["wave", "circle"]),
  logo("lg-circle-bars", "עיגול פסים", "Circle bars", "circle", "bars", "engrave", "heebo", "none", ["bars", "circle"]),
  logo("lg-plaque-chevron", "שברון לוח", "Plaque chevron", "plaque", "chevron", "plaque", "cinzel", "hairline", ["chevron", "plaque"]),
  logo("lg-plaque-oval", "לוח אובלי", "Plaque oval", "plaque", "oval", "engrave", "cormorant", "double", ["oval", "engrave"]),
  logo("lg-arch-sun", "קשת שמש", "Arch sun", "arch", "sun", "plaque", "italiana", "none", ["sun", "arch"]),
  logo("lg-slim-wave", "גל דק", "Slim wave", "slim", "wave", "sticker", "heebo", "none", ["wave", "slim"]),
  logo("lg-vertical-num", "מספר אנכי", "Vertical numeral", "tall", "numeral", "plaque", "cinzel", "none", ["numeral", "vertical", "plaque"]),
  logo("lg-corners-word", "מילה בפינות", "Cornered word", "square", "word", "decal", "cormorant", "corners", ["word", "corners"]),
];
